# Generated by Django 5.1.5 on 2025-01-18 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority_level',
            name='description',
        ),
        migrations.RemoveField(
            model_name='status',
            name='description',
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority_level',
            field=models.ForeignKey(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Migh', 'High')], on_delete=django.db.models.deletion.CASCADE, to='issues.priority_level'),
        ),
    ]
