# Generated by Django 5.1.5 on 2025-01-18 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20250117_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.priority_level'),
        ),
    ]
