# Generated by Django 5.1.5 on 2025-01-17 02:01

from django.db import migrations

def populate_teams_and_roles(apps, schema_editor):
    team = {
        "Alpha": "The A team",
        "Bravo": "The B team",
        "Charlie": "The C team",
    }

    roles = {
        "developer": "The person on the team who works on issues",
        "scrum master": "The team's coach",
        "product owner": "Team member in charge of defining product scope",
    }

    Team=apps.get_model("accounts", "Team")
    Roles=apps.get_model("accounts","Role")

    for key, value in team.items():
        team_obj = Team(name=key, description=value)
        team_obj.save()

    for key, value in roles.items():
        roles_obj = Roles(name=key, description=value)
        roles_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_teams_and_roles)
    ]
